<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>e331cd27-4cf0-4865-96bd-ac71bc10a1a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mI_38']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mI_38 > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f1ec7719-2196-4428-b480-e6f65ea6129c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>施設情報</value>
      <webElementGuid>9629fd24-c786-4388-b77b-38677edbc8d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mI_38&quot;)/span[1]</value>
      <webElementGuid>131b5d2d-be67-485e-b4ba-ff23568e9e1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mI_38']/span</value>
      <webElementGuid>626568ce-74af-410f-b320-50dfeced2763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='口座情報'])[1]/following::span[1]</value>
      <webElementGuid>90635ab7-55ae-4776-86f8-cd1d5c40efc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='休日管理'])[1]/following::span[2]</value>
      <webElementGuid>094b64e7-ba6f-4f35-9cad-d6d74b82c836</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='処遇改善等加算Ⅱ算定'])[1]/preceding::span[1]</value>
      <webElementGuid>0db89bf8-64c6-412d-b5b4-55b8aedb143e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='その他'])[1]/preceding::span[2]</value>
      <webElementGuid>b00d7208-739a-4941-8860-70a04faf090d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='施設情報']/parent::*</value>
      <webElementGuid>f9f24a7f-30f4-4c47-9fdf-7bbbe04612dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a[4]/div/span</value>
      <webElementGuid>fcd90268-bde0-4e5a-9d3c-f45b9041d0ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '施設情報' or . = '施設情報')]</value>
      <webElementGuid>21c39075-ca43-4471-b60d-cde6df68ce25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
