<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_</name>
   <tag></tag>
   <elementGuidId>5d41248e-f677-48ea-be46-8a288aeba170</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='button-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#button-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a554f7ec-66c4-4d38-aded-034c361e64e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-noty btn-primary</value>
      <webElementGuid>ca996792-796e-483a-9ed5-5d60a11635bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button-0</value>
      <webElementGuid>68ebdf6f-645c-4872-b20e-a0140f58bc18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>はい</value>
      <webElementGuid>c28be0d2-ed35-4ca9-b680-e73a45f1aa0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button-0&quot;)</value>
      <webElementGuid>c9d75a07-88cd-43bd-9611-37096da3814c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='button-0']</value>
      <webElementGuid>05c85979-0db6-4671-a365-bf453b085aeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='noty_1191790289877049000']/div[2]/button</value>
      <webElementGuid>b8107f9e-b1fa-4104-9d5a-6458fdc58219</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='選択した保育園を保存します。よろしいですか?'])[1]/following::button[1]</value>
      <webElementGuid>c6e3b206-7a1c-4b04-b32c-55e38d8a5835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'button-0', '&quot;', ')')])[1]/following::button[1]</value>
      <webElementGuid>92da784c-bd6b-48fd-8e8b-2483ff6c35d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='いいえ'])[1]/preceding::button[1]</value>
      <webElementGuid>8bdd1bab-c9b7-44ee-9430-67cb6d2ee4bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='はい']/parent::*</value>
      <webElementGuid>017efdbc-e71a-4911-83ad-c4e0bad70386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>b6155b67-7b43-44c6-9d7a-14dffb908026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'button-0' and (text() = 'はい' or . = 'はい')]</value>
      <webElementGuid>53a540a7-a3b9-4035-a708-6c913582c800</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
