<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__tel</name>
   <tag></tag>
   <elementGuidId>8504eec8-eee2-466f-b1f6-68f4800d8a2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4d710eba-2b9b-4d5a-9818-1fbd98fe431a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>8c932d41-d19b-4a4f-9cc8-2387316c389f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-style</value>
      <webElementGuid>29de042d-844f-4730-b963-a947e36f396e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d4c7f4ce-a9f1-42e2-a0d7-df238e0354b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>2e4e325a-c7e8-4fc6-bfc2-3cec40e621f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tel&quot;)</value>
      <webElementGuid>3de662eb-e1f5-41f5-a3fa-adf6c852d95a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tel']</value>
      <webElementGuid>b423d619-d14b-41fe-9d06-224824490e6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tbody[@id='sa1']/tr[11]/td[2]/input</value>
      <webElementGuid>8c9efcca-6dd3-48f5-8bc7-553e07ef32d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[11]/td[2]/input</value>
      <webElementGuid>24d0e1b3-0ff9-4597-802f-8b03357a29fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'tel' and @type = 'text' and @name = 'tel']</value>
      <webElementGuid>3df32228-b829-4057-bb0d-25406c628a6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
